/*  java_lang_Object.h
 *
 *      Autogenerated by j2oc (http://www.j2oc.com) at Sat Feb 13 00:50:52 PST 2010
 *
 *      Generated from missing methods and fields for java/lang/Object
 *      Generated template should be completed to make this work.
 */

// includes
#import <Foundation/Foundation.h>
#import "j2oc.h"

@class java_lang_Class;
@class java_lang_String;

@interface NSObject (category_java_lang_Object)

- (java_lang_Object *)clone_java_lang_Object__;
- (int32_t)hashCode_int__;
- (java_lang_Class *)getClass_java_lang_Class__;
- (BOOL)equals_boolean___java_lang_Object:(java_lang_Object *)v1_a;
- (java_lang_String *)toString_java_lang_String__;
- (void)__init_java_lang_Object__;

@end

