/*  java_lang_Class.h
 *
 *      Autogenerated by j2oc (http://www.j2oc.com) at Thu Feb 11 21:41:40 PST 2010
 *
 *      Generated from class java/lang/Class
 *      Do not change here; change in original class.
 */


// includes
#import <Foundation/Foundation.h>
#import "j2oc.h"

// class forwards
@class java_lang_String;



// class declaration
@interface J2OCClass (category_java_lang_Class)

- (void)__init_java_lang_Class__;
- (java_lang_String *)getName_java_lang_String__;
- (java_lang_Class *)getSuperclass_java_lang_Class__;
- (java_lang_String *)toString_java_lang_String__;

- (java_lang_Class *)getComponentType_java_lang_Class__;
- (BOOL)isInstance_boolean___java_lang_Object:(java_lang_Object *)v1_a;
- (BOOL)desiredAssertionStatus_boolean__;

@end

